"""Add coding workspaces and approvals

Revision ID: d8f9c5a9b461
Revises: d802d1f7cdd6
Create Date: 2026-09-22 22:29:26.942790
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d8f9c5a9b461"
down_revision: str | None = "d802d1f7cdd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coding_workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "READY",
                "ACTIVE",
                "WAITING_APPROVAL",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="workspace_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("repository_source", sa.String(length=300), nullable=False),
        sa.Column("workspace_key", sa.String(length=100), nullable=False),
        sa.Column("volume_name", sa.String(length=160), nullable=False),
        sa.Column("baseline_git_head", sa.String(length=40), nullable=True),
        sa.Column("current_git_head", sa.String(length=40), nullable=True),
        sa.Column("final_git_head", sa.String(length=40), nullable=True),
        sa.Column("diff_hash", sa.String(length=64), nullable=True),
        sa.Column("tree_hash", sa.String(length=64), nullable=True),
        sa.Column("file_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("test_command", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_checkpoint_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_coding_workspaces_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["workflow_steps.id"],
            name=op.f("fk_coding_workspaces_step_id_workflow_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_coding_workspaces_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coding_workspaces")),
        sa.UniqueConstraint("agent_run_id", name="uq_coding_workspaces_agent_run_id"),
        sa.UniqueConstraint("step_id", name="uq_coding_workspaces_step_id"),
        sa.UniqueConstraint("volume_name", name="uq_coding_workspaces_volume"),
        sa.UniqueConstraint("workspace_key", name="uq_coding_workspaces_key"),
    )
    op.create_index(
        "ix_coding_workspaces_workflow_id", "coding_workspaces", ["workflow_id"], unique=False
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="approval_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("operation_id", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["workflow_steps.id"],
            name=op.f("fk_approval_requests_step_id_workflow_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_approval_requests_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["coding_workspaces.id"],
            name=op.f("fk_approval_requests_workspace_id_coding_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
        sa.UniqueConstraint("operation_id", name="uq_approval_requests_operation_id"),
        sa.UniqueConstraint(
            "workspace_id", "action_type", name="uq_approval_requests_workspace_action"
        ),
    )
    op.create_index("ix_approval_requests_status", "approval_requests", ["status"], unique=False)
    op.create_index(
        "ix_approval_requests_workflow_id", "approval_requests", ["workflow_id"], unique=False
    )
    op.create_table(
        "sandbox_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("execution_attempt_id", sa.UUID(), nullable=False),
        sa.Column("container_ref", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "STOPPED",
                name="sandbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("image", sa.String(length=200), nullable=False),
        sa.Column("resource_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("network_mode", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_reason", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_attempt_id"],
            ["execution_attempts.id"],
            name=op.f("fk_sandbox_executions_execution_attempt_id_execution_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["coding_workspaces.id"],
            name=op.f("fk_sandbox_executions_workspace_id_coding_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sandbox_executions")),
        sa.UniqueConstraint("container_ref", name="uq_sandbox_executions_container"),
    )
    op.create_index(
        "ix_sandbox_executions_workspace_id", "sandbox_executions", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_checkpoints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("git_head", sa.String(length=40), nullable=False),
        sa.Column("diff_hash", sa.String(length=64), nullable=False),
        sa.Column("tree_hash", sa.String(length=64), nullable=False),
        sa.Column("file_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("operation_id", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence_number >= 1",
            name=op.f("ck_workspace_checkpoints_workspace_checkpoint_sequence_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["coding_workspaces.id"],
            name=op.f("fk_workspace_checkpoints_workspace_id_coding_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_checkpoints")),
        sa.UniqueConstraint(
            "workspace_id", "operation_id", name="uq_workspace_checkpoint_operation"
        ),
        sa.UniqueConstraint(
            "workspace_id", "sequence_number", name="uq_workspace_checkpoint_sequence"
        ),
    )
    op.create_index(
        "ix_workspace_checkpoints_workspace_id",
        "workspace_checkpoints",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "sandbox_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_tool_call_id", sa.UUID(), nullable=True),
        sa.Column("command_type", sa.String(length=100), nullable=False),
        sa.Column("argv", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "TIMED_OUT",
                "INTERRUPTED",
                name="sandbox_command_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout_excerpt", sa.Text(), nullable=True),
        sa.Column("stderr_excerpt", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "timeout_ms > 0", name=op.f("ck_sandbox_commands_sandbox_command_timeout_positive")
        ),
        sa.ForeignKeyConstraint(
            ["agent_tool_call_id"],
            ["agent_tool_calls.id"],
            name=op.f("fk_sandbox_commands_agent_tool_call_id_agent_tool_calls"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["coding_workspaces.id"],
            name=op.f("fk_sandbox_commands_workspace_id_coding_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sandbox_commands")),
    )
    op.create_index(
        "ix_sandbox_commands_tool_call_id", "sandbox_commands", ["agent_tool_call_id"], unique=False
    )
    op.create_index(
        "ix_sandbox_commands_workspace_id", "sandbox_commands", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sandbox_commands_workspace_id", table_name="sandbox_commands")
    op.drop_index("ix_sandbox_commands_tool_call_id", table_name="sandbox_commands")
    op.drop_table("sandbox_commands")
    op.drop_index("ix_workspace_checkpoints_workspace_id", table_name="workspace_checkpoints")
    op.drop_table("workspace_checkpoints")
    op.drop_index("ix_sandbox_executions_workspace_id", table_name="sandbox_executions")
    op.drop_table("sandbox_executions")
    op.drop_index("ix_approval_requests_workflow_id", table_name="approval_requests")
    op.drop_index("ix_approval_requests_status", table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_coding_workspaces_workflow_id", table_name="coding_workspaces")
    op.drop_table("coding_workspaces")
    # ### end Alembic commands ###
